// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RR4yCtx0ZdVEo6jqDyvPRVwmF_gDmKI',
    appId: '1:887904815508:web:28cf9e4d548abdc79aa781',
    messagingSenderId: '887904815508',
    projectId: 'product-entry-manager',
    authDomain: 'product-entry-manager.firebaseapp.com',
    storageBucket: 'product-entry-manager.firebasestorage.app',
    measurementId: 'G-R2DNKF8PY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvwLkSFKCN2XH-y_JqSbqXPGAXlmlFK4',
    appId: '1:887904815508:android:a56dc320c4499cf59aa781',
    messagingSenderId: '887904815508',
    projectId: 'product-entry-manager',
    storageBucket: 'product-entry-manager.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RR4yCtx0ZdVEo6jqDyvPRVwmF_gDmKI',
    appId: '1:887904815508:web:717006e93b30be0f9aa781',
    messagingSenderId: '887904815508',
    projectId: 'product-entry-manager',
    authDomain: 'product-entry-manager.firebaseapp.com',
    storageBucket: 'product-entry-manager.firebasestorage.app',
    measurementId: 'G-Y8444BJ25R',
  );
}
